include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 필수 규칙
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_check_on_nullable_type_parameter
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_typing_uninitialized_variables
    - sort_child_properties_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_getters_setters
    - unnecessary_null_in_if_null_operators
    - use_key_in_widget_constructors
    - valid_regexps

    # 성능 관련 규칙
    - avoid_function_literals_in_foreach_calls
    - avoid_slow_async_io
    - prefer_contains

    # 보안 관련 규칙
    - secure_pubspec_urls

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
