// Mocks generated by Mockito 5.4.4 from annotations
// in nubilab/test/presentation/viewmodels/air_quality_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nubilab/core/network/network_info.dart' as _i6;
import 'package:nubilab/data/datasources/air_quality_local_datasource.dart'
    as _i5;
import 'package:nubilab/data/models/air_quality.dart' as _i2;
import 'package:nubilab/domain/usecases/get_air_quality_usecase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAirQualityResponse_0 extends _i1.SmartFake
    implements _i2.AirQualityResponse {
  _FakeAirQualityResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAirQualityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAirQualityUseCase extends _i1.Mock
    implements _i3.GetAirQualityUseCase {
  MockGetAirQualityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AirQualityResponse> execute({
    required String? sidoName,
    int? pageNo = 1,
    int? numOfRows = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #sidoName: sidoName,
            #pageNo: pageNo,
            #numOfRows: numOfRows,
          },
        ),
        returnValue:
            _i4.Future<_i2.AirQualityResponse>.value(_FakeAirQualityResponse_0(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #sidoName: sidoName,
              #pageNo: pageNo,
              #numOfRows: numOfRows,
            },
          ),
        )),
      ) as _i4.Future<_i2.AirQualityResponse>);
}

/// A class which mocks [AirQualityLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAirQualityLocalDataSource extends _i1.Mock
    implements _i5.AirQualityLocalDataSource {
  MockAirQualityLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveAirQualityData({
    required String? sidoName,
    required _i2.AirQualityResponse? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAirQualityData,
          [],
          {
            #sidoName: sidoName,
            #data: data,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.AirQualityResponse?> getAirQualityData(String? sidoName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAirQualityData,
          [sidoName],
        ),
        returnValue: _i4.Future<_i2.AirQualityResponse?>.value(),
      ) as _i4.Future<_i2.AirQualityResponse?>);

  @override
  _i4.Future<void> deleteAirQualityData(String? sidoName) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAirQualityData,
          [sidoName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isAirQualityDataCached(String? sidoName) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAirQualityDataCached,
          [sidoName],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
